package lk.ijse.hospitel.util;

public enum Role {
    ADMIN,DOCTOR,PHARMACIST,RECEPTIONIST,LOGOUT,ADD_DOCTOR,ADMIN_DASH,SIGNUP,ADD_NURSE,ADD_PHARMACIST,ADD_RECEPTIONIST,ADD_MEDICINE,ADD_SUPPLIER,DOCTOR_AVAILABILITY,RECEPTION_DASH,ADD_PATIENT,APPOINTMENT,PAYMENT_RECEP,PATIENT_DETAILS,RECEIPT,CHOOSE_APPOINTMENT,ORDER;
}
